DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;

CREATE TABLE GENRES(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255)
);

CREATE TABLE AUTHORS(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255),
  SURNAME VARCHAR(255)
);

CREATE TABLE BOOKS(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255),
  AUTHOR_ID INT NOT NULL REFERENCES AUTHORS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
  GENRE_ID INT NOT NULL REFERENCES GENRES(ID) ON DELETE CASCADE ON UPDATE CASCADE
);