DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;

CREATE TABLE GENRES(
  ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  NAME TEXT
);

CREATE TABLE AUTHORS(
  ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  NAME TEXT,
  SURNAME TEXT
);

CREATE TABLE BOOKS(
  ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  NAME TEXT,
  AUTHOR_ID INTEGER NOT NULL REFERENCES AUTHORS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
  GENRE_ID INTEGER NOT NULL REFERENCES GENRES(ID) ON DELETE CASCADE ON UPDATE CASCADE
);